[package]
name = "naga-agal"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
bitflags = "2.3.2"
naga = { workspace = true }
num-derive = "0.3.3"
num-traits = "0.2.15"

[dev-dependencies]
insta = "1.30.0"
naga = { workspace = true, features = ["wgsl-out", "validate"] }
