[package]
name = "naga-agal"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
bitflags = "2.1.0"
naga = "0.12.0"
num-derive = "0.3.3"
num-traits = "0.2.15"

[dev-dependencies]
insta = "1.29.0"
naga = { version = "0.12.0", features = ["wgsl-out", "validate"] }
