[package]
name = "build_playerglobal"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
convert_case = "0.6.0"
proc-macro2 = "1.0.66"
quote = "1.0.32"
swf = { path = "../../swf" }
clap = {version = "4.3.19", features = ["derive"]}
serde = {version = "1.0.175", features = ["derive"]}
serde-xml-rs = "0.6.0"
colored = "2.0.4"
regex = "1.9.1"
walkdir = "2.3.3"
